- include: aliyun-source.yml

- include: docker-source.yml

- name: install curl
  apt: name=curl state=latest update_cache=yes cache_valid_time=1209600

- name: install apt-transport-https
  apt: name=apt-transport-https state=latest

- name: install ca-certificates
  apt: name=ca-certificates state=latest

- name: add apt-key for docker engine
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- shell: uname -r
  register: uname_value

- name: install linux-image-extra
  apt: name=linux-image-extra-{{ uname_value.stdout }} state=present

#- name: install docker-engine
#  apt: name=docker-engine state=latest
#  notify: start docker

- name: install docker
  shell: curl -sSL http://acs-public-mirror.oss-cn-hangzhou.aliyuncs.com/docker-engine/internet | sh -

- include: registry-mirror.yml