- include: aliyun-source.yml

- include: docker-source.yml

- name: install curl
  apt: name=curl state=latest update_cache=yes cache_valid_time=1209600

- name: install apt-transport-https
  apt: name=apt-transport-https state=latest

- name: install ca-certificates
  apt: name=ca-certificates state=latest

- name: install linux-image-extra
  shell: apt-get install linux-image-extra-$(uname -r)

- include: registry-mirror.yml

#- name: install docker-engine
#  apt: name=docker-engine state=latest
#  notify: start docker

- name: install docker
  shell: curl -sSL http://acs-public-mirror.oss-cn-hangzhou.aliyuncs.com/docker-engine/internet | sh -
  notify: start docker