- name: create docker.service.d directory replace
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: dockerhub with registry-mirror accelerator
  template: src=mirror.conf.j2 dest=/etc/systemd/system/docker.service.d/mirror.conf

- name: overwrite DOCKER_OPTS
  template: src=docker.j2 dest=/etc/default/docker
  notify: start docker