- name: install dcos nodes software prerequisites
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=1209600
  with_items:
      - tar
#      - xz
      - unzip
      - curl
      - ipset

