- name: install pip
  apt: name=python-pip state=latest update_cache=yes cache_valid_time=1209600

- name: install docker-py
  pip:
    name: "{{ item }}"
  with_items:
    - six
    - docker-py

- name: deploy zookeeper
  docker:
    name: mesos-zookeeper
    image: mesoscloud/zookeeper:3.4.8-ubuntu
    net: host
    expose:
    - 2181
    - 2888
    - 3888
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    volumes:
    - /var/data/zookeeper:/tmp/zookeeper
    restart_policy: always
    env:
      MYID: "{{ zookeeper_myid }}"
      SERVERS: "{{ zookeeper_servers }}"
    state: restarted