# CAN ONLY RUN ONCE
#- hosts: rancher_manager
#  sudo: yes
#  roles:
#    - docker
#  vars:
#    registry_mirror: https://9pukxhyh.mirror.aliyuncs.com

#- hosts: rancher_manager
#  sudo: yes
#  roles:
#    - rancher

- hosts: rancher_host
  sudo: yes
  roles:
    - docker
  vars:
    registry_mirror: https://9pukxhyh.mirror.aliyuncs.com
